# ##############################################################
#                    ServerConnect (By rexbut)                 #
# ##############################################################
noPermission: '&cYou don''t have permissions for that server!'